### ISSUE TITLE
PHP 5.3.x support

### ISSUE THREAD

**Issue by aleross** [Mashape/unirest-php#73]
Hi,

I installed Unirest from source. Is there no way to use it with PHP 5.3.x? I noticed Request:426 calls `hex2bin()`, which is missing from PHP 5.3.x. Are there other incompatibilities with 5.3.x? It would be nice if the PHP version requirement were made clearer on the README.md.

Thank you

**Comment by ahmadnassri** [comment]
we removed support to PHP 5.3 with [v2.0.0](https://github.com/Mashape/unirest-php/releases/tag/2.0.0) removed since PHP 5.3 reached [EOL on 14 Aug 2014](http://php.net/eol.php) meaning it will not be supported by Zend and major hosting providers, so it does not make much sense for us to support it either in future versions.

that said, you can always download previous versions *(most recent before the change is [v1.2.1](https://github.com/Mashape/unirest-php/releases/tag/1.2.1))* which are fully functional, just lacking newly added features in v2.x.x

on a personal note, I would strongly recommend updating from PHP 5.3 to for many security fixes and performance enhancements.

**Comment by aleross** [comment]
Thanks. Fyi, major (conservative) Linux distros like CentOS still only package PHP 5.3.x in their included repositories. I would consider making the 5.4.x requirement a bit more obvious.
